### ISSUE TITLE
Error: template: docassemble/templates/docassemble-secret.yml:12:39

### ISSUE THREAD

**Issue by wsmolkowski** [jhpyle/charts#6]
When wanna use our database not inside of cluster:
❯ helm upgrade --namespace docassemble docassemble jhpyle/docassemble --install  -f ../helm/docassemble-ca-central-1-1-values.yaml
Release "docassemble" does not exist. Installing it now.
Error: template: docassemble/templates/docassemble-secret.yml:12:39: executing "docassemble/templates/docassemble-secret.yml" at <b64enc>: invalid value; expected string
 
docassemble-ca-central-1-1-values.yaml:
 
    db.prefix: "mysql://"
    db.host: aurora-xxxxxx.ca-central-1.rds.amazonaws.com
    db.name: db
    db.user: du_user
    db.password: "password"
 
it not working with
 
    db.password: password

**Comment by jhpyle** [comment]
If you are giving values to Helm with a YAML file, the format of the YAML file would need to be:

```
inClusterPostgres: false
db:
  prefix: "mysql://"
  host: aurora-xxxxxx.ca-central-1.rds.amazonaws.com
  name: db
  user: du_user
  password: "password"
```

You can only use the `.` notation (e.g. `db.password`) when using `helm --set` to set value overrides.
